name: Keep VPS Online

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Connect to VPS
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} user@your-vps-ip-address "command-to-start-your-server"
